name: example-workflow
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        if: github.ref == '/refs/heads/dev' 
      - name: Trigger notebook in Dev
        uses: ShaikVasid/run-notebook@v0
        with:
          databricks-host: https://adb-1171939023690387.7.azuredatabricks.net/
          databricks-token: ${{ secrets.DATABRICKS_DEV_TOKEN }}
      - run: |
          npm install
      - run: |
          npm run all
        if: github.ref == '/refs/heads/main'			
      - name: Trigger notebook in prod
        uses: ShaikVasid/run-notebook@v0
        with:
          databricks-host: https://adb-2363935646913262.2.azuredatabricks.net/
          databricks-token: ${{ secrets.DATABRICKS_PROD_TOKEN }}
      - run: |
          npm install
      - run: |
          npm run all
